import React from "react";
import ForgetPassword from "../components/AuthForms/ForgetPassword";
import Head from "next/head";

function ForgotPasswordPage() {
  return (
    <div>
      <Head>
        <title>Forgot Password | LangWays</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <ForgetPassword />
    </div>
  );
}

export default ForgotPasswordPage;
