import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="home-banner">
          <div className="container">
            <div className="grid grid-cols-11">
              <div className="col-span-6">
                <h1 className="headline">
                  Connecting and preserving the world through languages
                </h1>
                <p className="mb-12">
                  Lorem ipsum dolor sit amet consectetur adipisicing elit.
                  Debitis quisquam cupiditate nihil corporis commodi animi sint
                  doloremque numquam aliquid itaque.
                </p>
                <Link href="/translators">
                  <a className="btn btn-yellow mr-4 shadow-xl">Find Provider</a>
                </Link>
                <Link href="/translator-signup">
                  <a className="btn btn-outline">Start Translating</a>
                </Link>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
