import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import AvailableServices from "../components/LandingPage/AvailableServices";
import FeaturedProviders from "../components/LandingPage/FeaturedProviders";
import Testimonials from "../components/LandingPage/Testimonials";
import Footer from "../components/LandingPage/Footer";
import HowItWorks from "../components/LandingPage/HowItWorks";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Home | True Words Connect</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.svg" />
      </Head>

      <main className="bg-light-blue">
        <div className="home-banner">
          <div className="container">
            <div className="grid grid-cols-11 flex items-end">
              <div className="col-span-11 md:col-span-6">
                <h1 className="headline text-center md:text-left">
                  Connecting People Through Languages
                </h1>
                <p className="mb-12 text-center md:text-left">
                  Where there is language, you will find a community, a culture, and an identity. From translation
                  and language learning to localization, Truewords Connect has all your language needs, all on one
                  platform.
                </p>
                <div className="text-center md:text-left">
                  <Link href="/providers">
                    <a className="btn btn-yellow mr-4 shadow-xl">
                      Find a Provider
                    </a>
                  </Link>
                  <Link href="/provider-signup">
                    <a className="btn btn-outline">Become A Provider</a>
                  </Link>
                </div>
              </div>
              <div className="col-span-11 md:col-span-5 hidden md:block">
                <div className="relative h-96">
                  <Image src="/home.svg" alt="" layout="fill" />
                </div>
              </div>
            </div>
          </div>
        </div>
        <div className="container py-32">
          <AvailableServices />
        </div>
        <div className="container py-32">
          <HowItWorks />
        </div>
        <div className="container py-32">
          <FeaturedProviders />
        </div>
        <div className="container py-32">
          <Testimonials />
        </div>
      </main>
      <Footer />
    </div>
  );
}
