import { useEffect } from "react";
import { useRouter } from "next/router";
import { useFirebaseAuth } from "../context/authContext";
import Login from "../components/AuthForms/Login";
import Head from "next/head";

export default function LoginPage() {
  const router = useRouter();
  const { loading, authUser } = useFirebaseAuth();

  useEffect(() => {
    if (!loading && authUser) router.push("/providers");
  }, [authUser, loading, router]);
  return (
    <>
      <Head>
        <title>Log In | LangWays</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <Login />
    </>
  );
}
