import React from "react";

function PrivacyPolicyPage() {
  return (
    <div className="bg-light-blue min-h-screen flex items-center">
      <div className="container mt-32">
        <div className="max-w-2xl mx-auto">
          <h1 className="font-bold text-3xl mb-8">Privacy policy</h1>
          <div className="flex items-center gap-2 mb-4">
            <h4 className="font-bold">Last updated:</h4>
            <p className=" italic">November 23, 2021</p>
          </div>
          <p className="leading-7 mb-4">
            This Privacy Policy describes Our policies and procedures on the
            collection, use and disclosure of Your information when You use the
            Service and tells You about Your privacy rights and how the law
            protects You.
          </p>
          <p className="leading-7 mb-4">
            We use Your Personal data to provide and improve the Service. By
            using the Service, You agree to the collection and use of
            information in accordance with this Privacy Policy.
          </p>
          {/* Interpretation and Definitions */}
          <div className="">
            <h2 className="font-bold text-2xl mb-8">
              Interpretation and Definitions
            </h2>
            <h4 className="font-semibold text-lg mb-4">Interpretation</h4>
            <p className="leading-7 mb-4">
              The words of which the initial letter is capitalized have meanings
              defined under the following conditions. The following definitions
              shall have the same meaning regardless of whether they appear in
              singular or in plural.
            </p>
            <h4 className="font-semibold text-lg mb-4">Definitions</h4>
            <p className="leading-7 mb-4">
              For the purposes of this Privacy Policy:
            </p>
            <div className="ml-4">
              <p className="leading-7 mb-4">
                <span className="font-bold">Account </span>
                means a unique account created for You to access our Service or
                parts of our Service.
              </p>

              <p className="leading-7 mb-4">
                <span className="font-bold">Company </span>
                (referred to as either &quot;the Company&quot;, &quot;We&quot;,
                &quot;Us&quot; or &quot;Our&quot; in this Agreement) refers to
                Truewords Connect, 285 Windrow Crescent SW, Airdrie, Alberta
                T4B4K2.
              </p>

              <p className="leading-7 mb-4">
                <span className="font-bold">Cookies </span>
                are small files that are placed on Your computer, mobile device
                or any other device by a website, containing the details of Your
                browsing history on that website among its many uses.
              </p>

              <p className="leading-7 mb-4">
                <span className="font-bold">Country </span>
                refers to: Alberta, Canada
              </p>

              <p className="leading-7 mb-4">
                <span className="font-bold">Device </span>
                means any device that can access the Service such as a computer,
                a cellphone or a digital tablet.
              </p>

              <p className="leading-7 mb-4">
                <span className="font-bold">Personal Data </span>
                is any information that relates to an identified or identifiable
                individual.
              </p>

              <p className="leading-7 mb-4">
                <span className="font-bold">Service </span>
                refers to the Website.
              </p>

              <p className="leading-7 mb-4">
                <span className="font-bold">Service Provider </span>
                means any natural or legal person who processes the data on
                behalf of the Company. It refers to third-party companies or
                individuals employed by the Company to facilitate the Service,
                to provide the Service on behalf of the Company, to perform
                services related to the Service or to assist the Company in
                analyzing how the Service is used.
              </p>

              <p className="leading-7 mb-4">
                <span className="font-bold">Usage Data </span>
                refers to data collected automatically, either generated by the
                use of the Service or from the Service infrastructure itself
                (for example, the duration of a page visit).
              </p>

              <p className="leading-7 mb-4">
                <span className="font-bold">Website </span>
                refers to Truewords Connect, accessible from
                www.truewordsconnect.com
              </p>

              <p className="leading-7 mb-4">
                <span className="font-bold">You </span>
                means the individual accessing or using the Service, or the
                company, or other legal entity on behalf of which such
                individual is accessing or using the Service, as applicable.
              </p>
            </div>
          </div>
          {/* Collecting and Using Your Personal Data */}
          <div className="">
            <h2 className="font-bold text-2xl mb-8">
              Collecting and Using Your Personal Data
            </h2>
            <h4 className="font-semibold text-lg mb-4">
              Types of data collected
            </h4>
            <div className="">
              <h5 className="font-bold">Personal Data</h5>
              <p className="leading-7 mb-4">
                While using Our Service, We may ask You to provide Us with
                certain personally identifiable information that can be used to
                contact or identify You. Personally identifiable information may
                include, but is not limited to:
              </p>
              <ul className="list-disc ml-16 mb-6">
                <li>Email address</li>
                <li>First name and last name</li>
                <li>Phone number</li>
                <li>Address, State, Province, ZIP/Postal code, City</li>
                <li>Usage Data</li>
              </ul>
              <h5 className="font-bold">Usage Data</h5>
              <p className="leading-7 mb-4">
                Usage Data is collected automatically when using the Service.
              </p>
              <p className="leading-7 mb-4">
                Usage Data may include information such as Your Device&apos;s
                Internet Protocol address (e.g. IP address), browser type,
                browser version, the pages of our Service that You visit, the
                time and date of Your visit, the time spent on those pages,
                unique device identifiers and other diagnostic data.
              </p>
              <p className="leading-7 mb-4">
                When You access the Service by or through a mobile device, We
                may collect certain information automatically, including, but
                not limited to, the type of mobile device You use, Your mobile
                device unique ID, the IP address of Your mobile device, Your
                mobile operating system, the type of mobile Internet browser You
                use, unique device identifiers and other diagnostic data.
              </p>
              <p className="leading-7 mb-4">
                We may also collect information that Your browser sends whenever
                You visit our Service or when You access the Service by or
                through a mobile device.
              </p>
              <h5 className="font-bold">Tracking Technologies and Cookies</h5>
              <p className="leading-7 mb-4">
                We use Cookies and similar tracking technologies to track the
                activity on Our Service and store certain information. Tracking
                technologies used are beacons, tags, and scripts to collect and
                track information and to improve and analyze Our Service. The
                technologies We use may include:
              </p>
              <ul className="list-disc">
                <li>
                  <span className="font-bold">
                    Cookies or Browser Cookies.{" "}
                  </span>
                  A cookie is a small file placed on Your Device. You can
                  instruct Your browser to refuse all Cookies or to indicate
                  when a Cookie is being sent. However, if You do not accept
                  Cookies, You may not be able to use some parts of our Service.
                  Unless you have adjusted Your browser setting so that it will
                  refuse Cookies, our Service may use Cookies.
                </li>
                <li>
                  <span className="font-bold">Flash Cookies. </span>
                  Certain features of our Service may use local stored objects
                  (or Flash Cookies) to collect and store information about Your
                  preferences or Your activity on our Service. Flash Cookies are
                  not managed by the same browser settings as those used for
                  Browser Cookies. For more information on how You can delete
                  Flash Cookies, please read &quot;Where can I change the
                  settings for disabling, or deleting local shared
                  objects?&quot; available at
                  https://helpx.adobe.com/flash-player/kb/disable-local-shared-objects-flash.html#main_Where_can_I_change_the_settings_for_disabling__or_deleting_local_shared_objects_
                </li>
                <li>
                  <span className="font-bold">Web Beacons. </span>
                  Certain sections of our Service and our emails may contain
                  small electronic files known as web beacons (also referred to
                  as clear gifs, pixel tags, and single-pixel gifs) that permit
                  the Company, for example, to count users who have visited
                  those pages or opened an email and for other related website
                  statistics (for example, recording the popularity of a certain
                  section and verifying system and server integrity).
                </li>
              </ul>
              <p className="leading-7 mb-4">
                Cookies can be &quot;Persistent&quot; or &quot;Session&quot;
                Cookies. Persistent Cookies remain on Your personal computer or
                mobile device when You go offline, while Session Cookies are
                deleted as soon as You close Your web browser. Learn more about
                cookies: Cookies: What Do They Do?.
              </p>
              <p className="leading-7 mb-4">
                We use both Session and Persistent Cookies for the purposes set
                out below:
              </p>
              <div className="ml-8">
                <h5 className="font-bold">Necessary / Essential Cookies</h5>
                <p>
                  <span className="font-medium">Type: </span> Session Cookies
                </p>
                <p>
                  <span className="font-medium">Administered by: </span> Us
                </p>
                <p>
                  <span className="font-medium">Purpose: </span> These Cookies
                  are essential to provide You with services available through
                  the Website and to enable You to use some of its features.
                  They help to authenticate users and prevent fraudulent use of
                  user accounts. Without these Cookies, the services that You
                  have asked for cannot be provided, and We only use these
                  Cookies to provide You with those services.
                </p>

                <h5 className="font-bold">
                  Cookies Policy / Notice Acceptance Cookies
                </h5>
                <p>
                  <span className="font-medium">Type: </span> Persistent Cookies
                </p>
                <p>
                  <span className="font-medium">Administered by: </span> Us
                </p>
                <p>
                  <span className="font-medium">Purpose: </span> These Cookies
                  identify if users have accepted the use of cookies on the
                  Website.
                </p>

                <h5 className="font-bold">Functionality Cookies</h5>
                <p>
                  <span className="font-medium">Type: </span> Persistent Cookies
                </p>
                <p>
                  <span className="font-medium">Administered by: </span> Us
                </p>
                <p>
                  <span className="font-medium">Purpose: </span> These Cookies
                  allow us to remember choices You make when You use the
                  Website, such as remembering your login details or language
                  preference. The purpose of these Cookies is to provide You
                  with a more personal experience and to avoid You having to
                  re-enter your preferences every time You use the Website.
                </p>

                <h5 className="font-bold">Tracking and Performance Cookies</h5>
                <p>
                  <span className="font-medium">Type: </span> Persistent Cookies
                </p>
                <p>
                  <span className="font-medium">Administered by: </span>{" "}
                  Third-Parties
                </p>
                <p>
                  <span className="font-medium">Purpose: </span> These Cookies
                  are used to track information about traffic to the Website and
                  how users use the Website. The information gathered via these
                  Cookies may directly or indirectly identify you as an
                  individual visitor. This is because the information collected
                  is typically linked to a pseudonymous identifier associated
                  with the device you use to access the Website. We may also use
                  these Cookies to test new pages, features or new functionality
                  of the Website to see how our users react to them.
                </p>
              </div>
              <p className="leading-7 mb-4 mt-4">
                For more information about the cookies we use and your choices
                regarding cookies, please visit our Cookies Policy or the
                Cookies section of our Privacy Policy.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export default PrivacyPolicyPage;
