import React from "react";

function PrivacyPolicyPage() {
  return (
    <div className="bg-light-blue min-h-screen flex items-center">
      <div className="container mt-32">
        <div className="max-w-2xl mx-auto">
          <h1 className="font-bold text-3xl mb-8">Privacy policy</h1>
          <div className="flex items-center gap-2 mb-4">
            <h4 className="font-bold">Last updated:</h4>
            <p className=" italic">November 23, 2021</p>
          </div>
          <p className="leading-7 mb-4">
            This Privacy Policy describes Our policies and procedures on the
            collection, use and disclosure of Your information when You use the
            Service and tells You about Your privacy rights and how the law
            protects You.
          </p>
          <p className="leading-7 mb-4">
            We use Your Personal data to provide and improve the Service. By
            using the Service, You agree to the collection and use of
            information in accordance with this Privacy Policy.
          </p>
          <div className="">
            <h2 className="font-bold text-2xl mb-8">
              Interpretation and Definitions
            </h2>
            <h4 className="font-semibold text-lg mb-4">Interpretation</h4>
            <p className="leading-7 mb-4">
              The words of which the initial letter is capitalized have meanings
              defined under the following conditions. The following definitions
              shall have the same meaning regardless of whether they appear in
              singular or in plural.
            </p>
            <h4 className="font-semibold text-lg mb-4">Definitions</h4>
            <p className="leading-7 mb-4">
              For the purposes of this Privacy Policy:
            </p>
            <div className="ml-4">
              <p className="leading-7 mb-4">
                <span className="font-bold">Account </span>
                means a unique account created for You to access our Service or
                parts of our Service.
              </p>

              <p className="leading-7 mb-4">
                <span className="font-bold">Company </span>
                (referred to as either &quot;the Company&quot;, &quot;We&quot;,
                &quot;Us&quot; or &quot;Our&quot; in this Agreement) refers to
                Truewords Connect, 285 Windrow Crescent SW, Airdrie, Alberta
                T4B4K2.
              </p>

              <p className="leading-7 mb-4">
                <span className="font-bold">Cookies </span>
                are small files that are placed on Your computer, mobile device
                or any other device by a website, containing the details of Your
                browsing history on that website among its many uses.
              </p>

              <p className="leading-7 mb-4">
                <span className="font-bold">Country </span>
                refers to: Alberta, Canada
              </p>

              <p className="leading-7 mb-4">
                <span className="font-bold">Device </span>
                means any device that can access the Service such as a computer,
                a cellphone or a digital tablet.
              </p>

              <p className="leading-7 mb-4">
                <span className="font-bold">Personal Data </span>
                is any information that relates to an identified or identifiable
                individual.
              </p>

              <p className="leading-7 mb-4">
                <span className="font-bold">Service </span>
                refers to the Website.
              </p>

              <p className="leading-7 mb-4">
                <span className="font-bold">Service Provider </span>
                means any natural or legal person who processes the data on
                behalf of the Company. It refers to third-party companies or
                individuals employed by the Company to facilitate the Service,
                to provide the Service on behalf of the Company, to perform
                services related to the Service or to assist the Company in
                analyzing how the Service is used.
              </p>

              <p className="leading-7 mb-4">
                <span className="font-bold">Usage Data </span>
                refers to data collected automatically, either generated by the
                use of the Service or from the Service infrastructure itself
                (for example, the duration of a page visit).
              </p>

              <p className="leading-7 mb-4">
                <span className="font-bold">Website </span>
                refers to Truewords Connect, accessible from
                www.truewordsconnect.com
              </p>

              <p className="leading-7 mb-4">
                <span className="font-bold">You </span>
                means the individual accessing or using the Service, or the
                company, or other legal entity on behalf of which such
                individual is accessing or using the Service, as applicable.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export default PrivacyPolicyPage;
