import React, { useEffect } from "react";
import ProviderOnboarding from "../components/AuthForms/ProviderOnboarding";
import { useFirebaseAuth } from "../context/authContext";
import { useRouter } from "next/router";
import Head from "next/head";

function ProviderOnboardingPage() {
  const { authUser, loading } = useFirebaseAuth();
  const router = useRouter();
  useEffect(() => {
    if (!loading && !authUser) router.push("/providers");
  }, [authUser, loading, router]);
  return (
    <>
      <Head>
        <title>Onboarding | LangWays</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <ProviderOnboarding />
    </>
  );
}

export default ProviderOnboardingPage;
