import ProviderSignup from "../components/AuthForms/ProviderSignup";
import Head from "next/head";

function ProviderSignupPage() {
  return (
    <>
      <Head>
        <title>Sign Up | LangWays</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/langways-globe.png" />
      </Head>
      <ProviderSignup />
    </>
  );
}

export default ProviderSignupPage;
