import * as React from "react";
import { useRouter } from "next/router";
import ResetPassword from "../components/AuthForms/ResetPassword";
import { useFirebaseAuth } from "../context/authContext";
import Head from "next/head";

function ResetPasswordPage() {
  const router = useRouter();
  const { loading, authUser } = useFirebaseAuth();

  React.useEffect(() => {
    if (!loading && authUser) router.push("/providers");
  }, [authUser, loading, router]);
  React.useEffect(() => {
    if (!router.query.oobCode) router.push("/providers");
  }, []);
  return (
    <div>
      <Head>
        <title>Reset Password | LangWays</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/langways-globe.png" />
      </Head>
      <ResetPassword />
    </div>
  );
}

export default ResetPasswordPage;
